apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: atomsized-apps
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: git@github.com:kubeden/clopus-preview-environments.git
    targetRevision: main
    path: infrastructure/applications/atomsized.com
    directory:
      recurse: true
      exclude: "app-of-apps.yml"
  destination:
    server: https://kubernetes.default.svc
    namespace: atomsized
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
