apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: github-token
  namespace: argocd
spec:
  encryptedData:
    token: AgC7gZj9UKNvb+2UQLL+7cgRhbp0auQCrfpvs5CbGgOxv99U8Z4vR0VJ/jom0rPr+Icxi7lp2F1YTV9KjWtHV/NgSeqUyLbwW5rhsjPrJ1kuBwOPKlKtDmBALMRSslc+tgUPa/uguYUNdoP3LiXLDAw+r389kMyL9SkgVr+kmq9widxrojOefsbVEgb2LYw005Yg5Y5PgcXTZv39md01vLJauuL8smxHXA9Ha7cPLzpxLRBkoWDAAXtk55WSG8vMGmWgoP8EB+dXs4k/YyHV5Ul5Zjr4gre9qA/JHPtWZThlWLP6HoXECliH6LI3ffZSOKGwuFDtCZgbgLnvcgnOz4oXyE/7dVTNSRtg+jdE5Zg38VPmO+DT3E+DWyC4w9lxyXP31RPmGtV0i/JRk4pxhS3Aga6OUa65ln5KvU/k/kyFSB7UhVYf9m9g5DM9hYVPEIxuJJO+aOWqs+MbaB0nnWmntcQo3ZYWsqoU0q83E6bLbdxMSvTxZJ9UH8/9h0fGHHrda6nnauIPH+iqEcZU5T4yAyNdXUGLENEnWbQ8V7YsRkIBKqwOBC4NB8ZzRSk4vpKe71UaAayM4rAvfEEXKXXf5ab87YgokvaOpwvJQrWx15NIJl6ZC7ucUKvLSv2gFqpL23t/j8B7khzzjmOjMd0+c1FKzRCxoHHduRr6uihUtkyK1521ouB74ZlF4w4qEd1TGFf2+Pg9l9znL6Xm8SMln16+Two78IFpvu56/i1O2Hb/k+PrKDG8VPx9Xo3lcFxlgoHbdQxhnK6CQR9BEnoYPS4ThyU9Qo21IQsXCnZCUl5oyL672McvegZHUbk=
  template:
    metadata:
      name: github-token
      namespace: argocd
    type: Opaque
